version: 2
jobs:
  build-common: &common-build
    docker:
      - image: node
    working_directory: ~/diff2html-cli
    steps: &common-steps
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: npm run build
      - run: npm run coverage

  build-latest: &latest-build
    docker:
      - image: node
    working_directory: ~/diff2html-cli
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn run test
      - run: yarn run lint
      - run: npm run coverage
      - run: yarn run codacy

  build-node_8:
    <<: *common-build
    docker:
      - image: node:8

  build-node_9:
    <<: *common-build
    docker:
      - image: node:9

  build-node_10:
    <<: *common-build
    docker:
      - image: node:10

  build-node_11:
    <<: *common-build
    docker:
      - image: node:11

  build-node_12:
    <<: *latest-build
    docker:
      - image: node:12

workflows:
  version: 2
  build:
    jobs:
      - build-node_8
      - build-node_9
      - build-node_10
      - build-node_11
      - build-node_12
